# Generated by Django 2.2.1 on 2020-11-15 13:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='screen1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='screenshot1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='screen2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='screenshot2'),
        ),
    ]
