# Generated by Django 3.1.2 on 2020-10-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='stay', max_length=20),
            preserve_default=False,
        ),
    ]
